const CARDS = {
    0: [
        'Todos toman',
        'Poder del dedo',
        'Cascada',
        'Regla',
        'Juego de la caja',
        'Palabra que rima',
        'Izquierda toma',
        'Tu tomas',
        'Derecha toma',
        'Bloquear palabra',
        'Escudo Permanente',
        'Rey 1',
        'Pregunton',
        'Caricachupas'
    ],
    1: [
        'Todos toman',
        'Poder del dedo',
        'Cascada',
        'Regla',
        'Juego de la caja',
        'Palabra que rima',
        'Izquierda toma',
        'Tu tomas',
        'Derecha toma',
        'Bloquear palabra',
        'Escudo Permanente',
        'Rey 2',
        'Pregunton',
        'Caricachupas'
    ],
    2: [
        'Todos toman',
        'Poder del dedo',
        'Cascada',
        'Regla',
        'Juego de la caja',
        'Palabra que rima',
        'Izquierda toma',
        'Tu tomas',
        'Derecha toma',
        'Bloquear palabra',
        'Escudo Permanente',
        'Rey 3',
        'Pregunton',
        'Caricachupas'
    ],
    4: [
        'Todos toman',
        'Poder del dedo',
        'Cascada',
        'Regla',
        'Juego de la caja',
        'Palabra que rima',
        'Izquierda toma',
        'Tu tomas',
        'Derecha toma',
        'Bloquear palabra',
        'Escudo Permanente',
        'Rey 4',
        'Pregunton',
        'Caricachupas'
    ]
}